name: "unit tests"

on:
    - push

jobs:
    run-tests:
        runs-on: "ubuntu-latest"
        container:
            image: "node:lts-alpine3.20"
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4.1.1"
                with:
                    fetch-depth: 0

            -   name: "Execute JEST"
                run: "npm run tests"
